// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuLvdo10P2-Si-EONm9tT3RtR7gtVIEPY',
    appId: '1:476101419378:web:f1518c1615243d5d093deb',
    messagingSenderId: '476101419378',
    projectId: 'sbi-demo-pro',
    authDomain: 'sbi-demo-pro.firebaseapp.com',
    storageBucket: 'sbi-demo-pro.firebasestorage.app',
    measurementId: 'G-4JG42EPY33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkP6AQrjGbanw2h1PwLS6PS34BtJP20J4',
    appId: '1:476101419378:android:d16faa0e1da2d5fa093deb',
    messagingSenderId: '476101419378',
    projectId: 'sbi-demo-pro',
    storageBucket: 'sbi-demo-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHbHrPlBEEavaXXk88s_DYxfyfutxzWYk',
    appId: '1:476101419378:ios:20db467a215617d5093deb',
    messagingSenderId: '476101419378',
    projectId: 'sbi-demo-pro',
    storageBucket: 'sbi-demo-pro.firebasestorage.app',
    iosBundleId: 'com.example.sbiDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHbHrPlBEEavaXXk88s_DYxfyfutxzWYk',
    appId: '1:476101419378:ios:20db467a215617d5093deb',
    messagingSenderId: '476101419378',
    projectId: 'sbi-demo-pro',
    storageBucket: 'sbi-demo-pro.firebasestorage.app',
    iosBundleId: 'com.example.sbiDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuLvdo10P2-Si-EONm9tT3RtR7gtVIEPY',
    appId: '1:476101419378:web:d837d7d91e97b5b6093deb',
    messagingSenderId: '476101419378',
    projectId: 'sbi-demo-pro',
    authDomain: 'sbi-demo-pro.firebaseapp.com',
    storageBucket: 'sbi-demo-pro.firebasestorage.app',
    measurementId: 'G-YVJHJSTELT',
  );

}