// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtuWLsBRCjIbFTacUL85YNZiPi016yTBo',
    appId: '1:1057047847304:web:9df9038dae760a55d89a3d',
    messagingSenderId: '1057047847304',
    projectId: 'sbi-demo-dev',
    authDomain: 'sbi-demo-dev.firebaseapp.com',
    storageBucket: 'sbi-demo-dev.firebasestorage.app',
    measurementId: 'G-CP7Y5K8D7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsJN5pFNFBbVeErSd0BI9aQjOW80VpAek',
    appId: '1:1057047847304:android:529459cabf3f47e0d89a3d',
    messagingSenderId: '1057047847304',
    projectId: 'sbi-demo-dev',
    storageBucket: 'sbi-demo-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhxyHdpP0i3xJFBdtZWBS5giy2eNXmnSU',
    appId: '1:1057047847304:ios:8143ce456d189c07d89a3d',
    messagingSenderId: '1057047847304',
    projectId: 'sbi-demo-dev',
    storageBucket: 'sbi-demo-dev.firebasestorage.app',
    iosBundleId: 'com.example.sbiDemo.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhxyHdpP0i3xJFBdtZWBS5giy2eNXmnSU',
    appId: '1:1057047847304:ios:800f7c6dfa47df8ed89a3d',
    messagingSenderId: '1057047847304',
    projectId: 'sbi-demo-dev',
    storageBucket: 'sbi-demo-dev.firebasestorage.app',
    iosBundleId: 'com.example.sbiDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtuWLsBRCjIbFTacUL85YNZiPi016yTBo',
    appId: '1:1057047847304:web:1a5339bfb3b667c6d89a3d',
    messagingSenderId: '1057047847304',
    projectId: 'sbi-demo-dev',
    authDomain: 'sbi-demo-dev.firebaseapp.com',
    storageBucket: 'sbi-demo-dev.firebasestorage.app',
    measurementId: 'G-K4EC89M6MH',
  );

}