// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuZwUvf--3JH3W5eYY5YNYHI_JBHi2Lx0',
    appId: '1:331313846384:web:cfa58681f2beab1c1efcb5',
    messagingSenderId: '331313846384',
    projectId: 'sbi-demo-staging',
    authDomain: 'sbi-demo-staging.firebaseapp.com',
    storageBucket: 'sbi-demo-staging.firebasestorage.app',
    measurementId: 'G-2S2PEW1VCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnuAsD0xKUljbN8tJRYAf6IGGzSV7Z-dU',
    appId: '1:331313846384:android:8fec905e8054967c1efcb5',
    messagingSenderId: '331313846384',
    projectId: 'sbi-demo-staging',
    storageBucket: 'sbi-demo-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4deTQcyRY02ctkFRn2aamCx2x6Uh89zg',
    appId: '1:331313846384:ios:2ddd90f51d5bf7d71efcb5',
    messagingSenderId: '331313846384',
    projectId: 'sbi-demo-staging',
    storageBucket: 'sbi-demo-staging.firebasestorage.app',
    iosBundleId: 'com.example.sbiDemo.staging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4deTQcyRY02ctkFRn2aamCx2x6Uh89zg',
    appId: '1:331313846384:ios:f4c6b84ed6e0d5a61efcb5',
    messagingSenderId: '331313846384',
    projectId: 'sbi-demo-staging',
    storageBucket: 'sbi-demo-staging.firebasestorage.app',
    iosBundleId: 'com.example.sbiDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuZwUvf--3JH3W5eYY5YNYHI_JBHi2Lx0',
    appId: '1:331313846384:web:46fa375d47a9a9291efcb5',
    messagingSenderId: '331313846384',
    projectId: 'sbi-demo-staging',
    authDomain: 'sbi-demo-staging.firebaseapp.com',
    storageBucket: 'sbi-demo-staging.firebasestorage.app',
    measurementId: 'G-915Q1XWJ0G',
  );

}